### ISSUE TITLE
DNS under local network (Stale)

### ISSUE THREAD

**Issue by nishp77** [NOXCIS/Worm-Hole#1]
Can I still point to my local server IP as DNS in my router?

**Comment by nishp77** [comment]
Sorry another question, I was trying to access the via wireguard outside of my network but couldn't get it working.. is it coz of my firewall where I have worm-hole?

**Comment by NOXCIS** [comment]
@nishp77  can you give more explanation on your setup

**Comment by NOXCIS** [comment]
I intended worm-hole to run on a VPS. However, I can make a branch for self hosting.

**Comment by NOXCIS** [comment]
@Drknz056 No Worm-Hole by design does not expose pihole. Because the container running on a docker private network without and exposed port. Meaning the only way to access the dashboard is through the VPN. However you can modify the docker-compose to do so. The Worm-Hole philosophy is to only expose the minimum amount of containers. Meaning only the WG-Dashboard, which should be blocked via firewall after configs are generated and distributed.
