### ISSUE TITLE
How do I run the script detached

### ISSUE THREAD

**Issue by Georgebobby** [NOXCIS/Worm-Hole#13]
Hello~~ thank you soooo much for the wonderful project. I was facing issues with wirehole but can't resolve and try different hole and it works. However, I'd like to know how I could run it in the background. I ran the installation script but the terminal gets occupied ... I end the ssh connect to the vps and it stops working...

**Comment by NOXCIS** [comment]
What's your setup

**Comment by NOXCIS** [comment]
Which one stops working the VPN or SSH session? 

- If SSH session
 Connecting to the VPN will break   your SSH session. Reconnect.

- If VPN 
 Something has gone terribly wrong    send screenshot of term output. Why because the script is running a docker stack and not a set of stand alone apps on the base is. Hence it uses the docker daemon.

**Comment by NOXCIS** [comment]
Can you attach screenshots
